version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - task_data:/app/data

  frontend:
    build: ./frontend
    ports:
      - "3009:80"
    depends_on:
      - backend

volumes:
  task_data:
