version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8009:8000"
    volumes:
      - task_data:/app/data

  frontend:
    build:
      context: ./frontend-react
    ports:
      - "3009:80"
    depends_on:
      - backend


volumes:
  task_data:
